export const IDENTITY_OPTIONS = "IDENTITY_OPTIONS";
export const AUTH_PROVIDER = "AUTH_PROVIDER";
export const USER_PROVIDER = "USER_PROVIDER";
export const TENANT_PROVIDER = "TENANT_PROVIDER";
export const PERMISSION_PROVIDER = "PERMISSION_PROVIDER";
export const EMAIL_PROVIDER = "EMAIL_PROVIDER";
export const DATABASE_CONNECTION = "DATABASE_CONNECTION";

export const SYSTEM_TENANT_ID = "00000000-0000-0000-0000-000000000000";
export const PLATFORM_ADMIN_ROLE_ID = "platform_admin";
export const DEFAULT_SYSTEM_ROLE_ID = "member";
