packages:
  - 'apps/*'
  - 'packages/*'
  - 'engine/sync/platform/*'
  - 'engine/sync/application/*'
  - 'engine/ai/*'
  - 'packages/pieces/platform/*'
  - 'packages/pieces/application/*'
  - 'packages/domain/*'

