packages:
  - 'apps/*'
  - 'packages/*'
  - 'engine/sync/platform/*'
  - 'engine/sync/application/*'
  - 'engine/sync/application/*/*'
  - 'engine/ai/*'
  - 'packages/pieces/platform/*'
  - 'packages/pieces/application/*'
  - 'packages/pieces/application/*/*'
  - 'packages/domain/*'

onlyBuiltDependencies:
  - '@nestjs/core'
  - '@swc/core'
  - 'esbuild'
  - 'sharp'

