packages:
  - 'apps/*'
  - 'packages/*'
  - 'packages/domain/*'
  - '!packages/domain/tms'
  - 'engine/sync/platform/*'
  - 'engine/ai/*'
  - 'sdk/*'
  - 'plugins/*/*'

onlyBuiltDependencies:
  - '@nestjs/core'
  - '@swc/core'
  - 'esbuild'
  - 'sharp'

