import {
    Injectable,
    InternalServerErrorException,
    BadGatewayException,
} from '@nestjs/common';
import { TokenManagerService } from '../connectivity/token-manager.service.js';
import { DrizzleDb } from '@nexiom/database';
import { sql } from 'drizzle-orm';
import { Redis } from 'ioredis';

export enum HttpMethod {
    GET = 'GET',
    POST = 'POST',
    PUT = 'PUT',
    PATCH = 'PATCH',
    DELETE = 'DELETE',
}

export interface HttpRequest {
    method: HttpMethod;
    url: string;
    headers?: Record<string, string>;
    body?: any;
    queryParams?: Record<string, string>;
    authentication?: {
        type: 'BEARER_TOKEN';
        token: string;
    };
}

export interface HttpResponse {
    status: number;
    headers: Record<string, string>;
    body: any;
}

interface InternalExecutionState {
    connectionId: string;
    workspaceId?: string;
}

/**
 * The HostHttpClient intercepts every single API request generated by an Activepieces action.
 * It is solely responsible for enterprise reliability: Distributed Rate Limiting, Retries, Audit Logs, and DLQ errors.
 */
@Injectable()
export class HostHttpClient {
    // A global AsyncLocalStorage map or static context to bind the current executing connectionId to generic fetch calls
    private static readonly executionState = new Map<string, InternalExecutionState>();

    constructor(
        private readonly tokenManager: TokenManagerService,
        private readonly db: DrizzleDb,
        private readonly redis: Redis,
    ) { }

    /**
     * Called by the Sync Engine right before executing `action.run()`.
     * Tells the client which Connection is currently responsible for the outgoing HTTP requests.
     */
    public static bindExecutionCtx(
        traceId: string,
        connectionId: string,
        workspaceId: string,
    ) {
        this.executionState.set(traceId, { connectionId, workspaceId });
    }

    public static unbindExecutionCtx(traceId: string) {
        this.executionState.delete(traceId);
    }

    async sendRequest(request: HttpRequest): Promise<HttpResponse> {
        // 1. Identify Context
        const token = request.authentication?.token;

        // 2. Distributed Rate Limiting (Redis)
        await this.enforceRateLimits(request.url);

        // 3. Execution with Retries & Interception
        const startTime = Date.now();
        const response = await this.executeWithRetries(request, token);
        const duration = Date.now() - startTime;

        // Parse Body
        const responseBody = await this.parseResponseBody(response);

        const payload: HttpResponse = {
            status: response.status,
            headers: Object.fromEntries(response.headers.entries()),
            body: responseBody,
        };

        // 4. Gateway Database Archival
        const trace = Array.from(HostHttpClient.executionState.values())[0];
        if (trace?.workspaceId) {
            this.archiveToGateway(trace.workspaceId, request, payload, duration);
        }

        return payload;
    }

    private async executeWithRetries(
        request: HttpRequest,
        token?: string,
    ): Promise<Response> {
        let attempt = 0;
        let response: Response | undefined;

        const { url, options } = this.buildFetchOptions(request, token);

        while (attempt < 3) {
            try {
                response = await fetch(url, options);

                this.throwIfTransientError(response);

                return response;
            } catch (err) {
                const errorMessage = err instanceof Error ? err.message : String(err);
                console.debug(`AP Http Request attempt ${attempt + 1} failed: ${errorMessage}`);

                attempt++;
                if (attempt >= 3) {
                    throw new InternalServerErrorException(
                        `Failed to execute outgoing AP request after 3 attempts. Last error: ${errorMessage}`,
                        { cause: err instanceof Error ? err : new Error(String(err)) }
                    );
                }
                await new Promise((res) => setTimeout(res, Math.pow(2, attempt) * 1000));
            }
        }
        throw new InternalServerErrorException('Unexpected retry loop termination');
    }

    private throwIfTransientError(response: Response) {
        if (!response.ok && [429, 502, 503, 504].includes(response.status)) {
            throw new BadGatewayException(
                `Transient Upstream Error: ${response.status}`,
            );
        }
    }

    private buildFetchOptions(request: HttpRequest, token?: string): { url: string; options: RequestInit } {
        const options: RequestInit = {
            method: request.method,
            headers: {
                'Content-Type': 'application/json',
                ...request.headers,
            },
            body: request.body ? JSON.stringify(request.body) : undefined,
        };

        if (token) {
            (options.headers as Record<string, string>)['Authorization'] = `Bearer ${token}`;
        }

        const urlParams = request.queryParams
            ? '?' + new URLSearchParams(request.queryParams).toString()
            : '';

        return {
            url: `${request.url}${urlParams}`,
            options,
        };
    }

    private async parseResponseBody(response: Response): Promise<any> {
        const text = await response.text();
        try {
            return JSON.parse(text);
        } catch (error) {
            const errorMessage = error instanceof Error ? error.message : String(error);
            console.debug(`Response body is not JSON: ${errorMessage}`);
            return text; // Keep as string if not JSON
        }
    }

    /**
     * Archives both the HTTP Request and HTTP Response natively into the Connection's specific physical DB workspace.
     */
    private async archiveToGateway(
        workspaceId: string,
        req: HttpRequest,
        res: HttpResponse,
        durationMs: number,
    ) {
        try {
            // Direct raw insertion to bypass schema boundaries, ensuring the log always hits the target workspace.
            await this.db.execute(sql`
        INSERT INTO ${sql.raw(`"${workspaceId}".gateway_logs`)} 
        (method, url, request_headers, request_body, response_status, response_headers, response_body, duration_ms, created_at)
        VALUES (
            ${req.method},
            ${req.url},
            ${JSON.stringify(req.headers ?? {})},
            ${JSON.stringify(req.body ?? {})},
            ${res.status},
            ${JSON.stringify(res.headers ?? {})},
            ${JSON.stringify(res.body ?? {})},
            ${durationMs},
            NOW()
        )
      `);
        } catch (e) {
            console.error(
                `[AUDIT_FAILURE] Could not archive gateway log for workspace ${workspaceId}`,
                e,
            );
        }
    }

    private async enforceRateLimits(url: string) {
        const domain = new URL(url).hostname;
        // Example primitive sliding window using Redis
        // In production, use token bucket or Redis Cell for high-throughput
        const key = `ratelimit:ap_vendor:${domain}`;
        const calls = await this.redis.incr(key);
        if (calls === 1) {
            await this.redis.expire(key, 60); // 1 minute window
        }
        if (calls > 1000) {
            // Delay explicitly to smooth out bursts, avoiding hard 429 errors from standard APIs
            await new Promise((res) => setTimeout(res, 3000));
        }
    }
}

/**
 * Singleton exported as exactly 'httpClient' to match the Activepieces framework signature.
 * Note: Must be injected / initialized by the Host Engine at startup.
 */
export const httpClient = new HostHttpClient(
    null as any, // Injected at run-time by NestJS
    null as any,
    null as any,
);
