import {
    Injectable,
    InternalServerErrorException,
    BadGatewayException,
} from '@nestjs/common';
import { TokenManagerService } from '../connectivity/token-manager.service.js';
import { DrizzleDb } from '@nexiom/database';
import { sql } from 'drizzle-orm';
import { Redis } from 'ioredis';

export enum HttpMethod {
    GET = 'GET',
    POST = 'POST',
    PUT = 'PUT',
    PATCH = 'PATCH',
    DELETE = 'DELETE',
}

export interface HttpRequest {
    method: HttpMethod;
    url: string;
    headers?: Record<string, string>;
    body?: any;
    queryParams?: Record<string, string>;
    authentication?: {
        type: 'BEARER_TOKEN';
        token: string;
    };
}

export interface HttpResponse {
    status: number;
    headers: Record<string, string>;
    body: any;
}

/** How long a trace context is retained before it is treated as expired (5 minutes). */
const EXECUTION_STATE_TTL_MS = 5 * 60 * 1000;

interface InternalExecutionState {
    connectionId: string;
    workspaceId?: string;
    createdAt: number;
}

/**
 * The HostHttpClient intercepts every single API request generated by an Activepieces action.
 * It is solely responsible for enterprise reliability: Distributed Rate Limiting, Retries, Audit Logs, and DLQ errors.
 */
@Injectable()
export class HostHttpClient {
    // A global AsyncLocalStorage map or static context to bind the current executing connectionId to generic fetch calls
    private static readonly executionState = new Map<string, InternalExecutionState>();
    /** Single shared cleanup timer — prevents one timer per bindExecutionCtx call. */
    private static cleanupTimer: ReturnType<typeof setInterval> | null = null;

    constructor(
        private readonly tokenManager: TokenManagerService,
        private readonly db: DrizzleDb,
        private readonly redis: Redis,
    ) { }

    /**
     * Called by the Sync Engine right before executing `action.run()`.
     * Tells the client which Connection is currently responsible for the outgoing HTTP requests.
     */
    public static bindExecutionCtx(
        traceId: string,
        connectionId: string,
        workspaceId: string,
    ) {
        this.executionState.set(traceId, { connectionId, workspaceId, createdAt: Date.now() });
        // Start a single shared cleanup interval — only if one isn't already running
        HostHttpClient.cleanupTimer ??= setInterval(
            () => HostHttpClient.purgeExpiredExecutionState(),
            EXECUTION_STATE_TTL_MS + 1000,
        );
    }

    public static getExecutionCtx(traceId: string): InternalExecutionState | undefined {
        const entry = this.executionState.get(traceId);
        if (!entry) return undefined;
        if (Date.now() - entry.createdAt > EXECUTION_STATE_TTL_MS) {
            // Expired — evict on access so the map doesn't retain stale state
            this.executionState.delete(traceId);
            return undefined;
        }
        return entry;
    }

    /** Removes all expired entries from the execution state map. Stops the interval when the map is empty. */
    public static purgeExpiredExecutionState() {
        const now = Date.now();
        for (const [id, state] of this.executionState.entries()) {
            if (now - state.createdAt > EXECUTION_STATE_TTL_MS) {
                this.executionState.delete(id);
            }
        }
        // Stop the interval when no entries remain to avoid keeping the process alive
        if (this.executionState.size === 0 && this.cleanupTimer) {
            clearInterval(this.cleanupTimer);
            this.cleanupTimer = null;
        }
    }

    public static unbindExecutionCtx(traceId: string) {
        this.executionState.delete(traceId);
    }

    async sendRequest(request: HttpRequest): Promise<HttpResponse> {
        // 1. Identify Context
        const token = request.authentication?.token;

        // 2. Distributed Rate Limiting (Redis)
        await this.enforceRateLimits(request.url);

        // 3. Execution with Retries & Interception
        const startTime = Date.now();
        const response = await this.executeWithRetries(request, token);
        const duration = Date.now() - startTime;

        // Parse Body
        const responseBody = await this.parseResponseBody(response);

        const payload: HttpResponse = {
            status: response.status,
            headers: Object.fromEntries(response.headers.entries()),
            body: responseBody,
        };

        // 4. Gateway Database Archival
        // Only use the explicitly injected trace header — no non-deterministic fallback.
        const traceId = request.headers?.['x-nexiom-trace-id'];
        const trace = traceId ? HostHttpClient.getExecutionCtx(traceId) : undefined;

        if (trace?.workspaceId) {
            // Pass the effective URL (with merged query params) from the actual fetch call for accurate audit logs
            this.archiveToGateway(trace.workspaceId, request, payload, duration, response.url);
        }

        return payload;
    }

    private async executeWithRetries(
        request: HttpRequest,
        token?: string,
    ): Promise<Response> {
        let attempt = 0;
        let response: Response | undefined;

        const { url, options } = this.buildFetchOptions(request, token);

        while (attempt < 3) {
            const controller = new AbortController();
            const timeout = setTimeout(() => controller.abort(), 10_000); // Fixed 10s per-attempt; backoff is handled by the sleep below

            try {
                response = await fetch(url, { ...options, signal: controller.signal });
                clearTimeout(timeout);

                this.throwIfTransientError(response);

                return response;
            } catch (err) {
                clearTimeout(timeout);
                const errorMessage = err instanceof Error ? err.message : String(err);
                console.debug(`AP Http Request attempt ${attempt + 1} failed: ${errorMessage}`);

                attempt++;
                if (attempt >= 3) {
                    throw new InternalServerErrorException(
                        `Failed to execute outgoing AP request after 3 attempts. Last error: ${errorMessage}`,
                        { cause: err instanceof Error ? err : new Error(String(err)) }
                    );
                }
                await new Promise((res) => setTimeout(res, Math.pow(2, attempt) * 1000));
            }
        }
        throw new InternalServerErrorException('Unexpected retry loop termination');
    }

    private throwIfTransientError(response: Response) {
        if (!response.ok && [429, 502, 503, 504].includes(response.status)) {
            throw new BadGatewayException(
                `Transient Upstream Error: ${response.status}`,
            );
        }
    }

    private buildFetchOptions(request: HttpRequest, token?: string): { url: string; options: RequestInit } {
        const options: RequestInit = {
            method: request.method,
            headers: {
                'Content-Type': 'application/json',
                ...request.headers,
            },
            body: request.body === undefined ? undefined : JSON.stringify(request.body),
        };

        if (token) {
            (options.headers as Record<string, string>)['Authorization'] = `Bearer ${token}`;
        }

        const effectiveUrl = new URL(request.url);
        if (request.queryParams) {
            // Safely merge params; preserves any query params already in request.url
            for (const [k, v] of new URLSearchParams(request.queryParams).entries()) {
                effectiveUrl.searchParams.append(k, v);
            }
        }

        return {
            url: effectiveUrl.toString(),
            options,
        };
    }

    private async parseResponseBody(response: Response): Promise<any> {
        const text = await response.text();
        try {
            return JSON.parse(text);
        } catch (error) {
            const errorMessage = error instanceof Error ? error.message : String(error);
            console.debug(`Response body is not JSON: ${errorMessage}`);
            return text; // Keep as string if not JSON
        }
    }

    /**
     * Archives both the HTTP Request and HTTP Response natively into the Connection's specific physical DB workspace.
     */
    private async archiveToGateway(
        workspaceId: string,
        req: HttpRequest,
        res: HttpResponse,
        durationMs: number,
        effectiveUrl: string,
    ) {
        try {
            // Secure gateway DB storage with proper SQL Identifier sanitization
            const schemaIdentifier = sql.identifier(workspaceId);
            const tableIdentifier = sql.identifier('gateway_logs');

            await this.db.execute(sql`
        INSERT INTO ${schemaIdentifier}.${tableIdentifier}
        (method, url, request_headers, request_body, response_status, response_headers, response_body, duration_ms, created_at)
        VALUES (
            ${req.method},
            ${this.sanitizeUrl(effectiveUrl)},
            ${JSON.stringify(this.sanitizeHeaders(req.headers ?? {}))},
            ${JSON.stringify(this.sanitizeBody(req.body ?? {}))},
            ${res.status},
            ${JSON.stringify(this.sanitizeHeaders(res.headers ?? {}))},
            ${JSON.stringify(this.sanitizeBody(res.body ?? {}))},
            ${durationMs},
            NOW()
        )
      `);
        } catch (e) {
            console.error(
                `[AUDIT_FAILURE] Could not archive gateway log for workspace ${workspaceId}`,
                e,
            );
        }
    }

    private async enforceRateLimits(url: string) {
        const domain = new URL(url).hostname;
        const key = `ratelimit:ap_vendor:${domain}`;

        // Atomic Lua script: INCR + EXPIRE only when the key is newly created (value == 1)
        // Prevents the INCR/EXPIRE race condition under concurrent callers
        const luaScript = `
            local count = redis.call('INCR', KEYS[1])
            if count == 1 then
                redis.call('EXPIRE', KEYS[1], ARGV[1])
            end
            return count
        `;
        const calls = await this.redis.eval(luaScript, 1, key, '60') as number;

        if (calls > 1000) {
            await new Promise((res) => setTimeout(res, 3000));
        }
    }

    private sanitizeHeaders(headers: Record<string, string>): Record<string, string> {
        const sensitiveKeys = new Set(['authorization', 'cookie', 'set-cookie', 'x-api-key', 'bearer']);
        const sanitized: Record<string, string> = {};
        for (const [key, value] of Object.entries(headers)) {
            if (sensitiveKeys.has(key.toLowerCase())) {
                sanitized[key] = '[REDACTED]';
            } else {
                sanitized[key] = value;
            }
        }
        return sanitized;
    }

    private sanitizeBody(body: any): any {
        if (!body) return body;

        // If stringified JSON, try to parse and redact
        let parsedBody = body;
        let isStringified = false;

        if (typeof body === 'string') {
            try {
                parsedBody = JSON.parse(body);
                isStringified = true;
            } catch {
                return body; // Plain text or unparseable, skip redact logic for now
            }
        }

        if (typeof parsedBody === 'object' && parsedBody !== null) {
            // Deep-clone before mutation to avoid modifying the caller's object.
            // structuredClone can throw for non-cloneable values (e.g. functions, DOM nodes)
            // so fall back to JSON round-trip for plain serializable objects.
            let sanitized: Record<string, any>;
            try {
                sanitized = structuredClone(parsedBody);
            } catch {
                try {
                    sanitized = JSON.parse(JSON.stringify(parsedBody)); // NOSONAR — intentional fallback when structuredClone throws DataCloneError
                } catch {
                    return body; // Unserializable — return original, don't risk mutation
                }
            }

            const sensitiveFields = ['password', 'token', 'secret', 'access_token', 'refresh_token', 'client_secret'];

            const redactRecursive = (obj: any) => {
                for (const key in obj) {
                    if (typeof obj[key] === 'object' && obj[key] !== null) {
                        redactRecursive(obj[key]);
                    } else if (sensitiveFields.some(sf => key.toLowerCase().includes(sf))) {
                        obj[key] = '[REDACTED]';
                    }
                }
            };

            redactRecursive(sanitized);
            return isStringified ? JSON.stringify(sanitized) : sanitized;
        }

        return body;
    }

    private sanitizeUrl(url: string): string {
        const sensitiveParams = new Set(['token', 'access_token', 'refresh_token', 'api_key', 'apikey', 'key', 'signature']);
        try {
            const parsed = new URL(url);
            for (const [paramKey] of parsed.searchParams.entries()) {
                if (sensitiveParams.has(paramKey.toLowerCase())) {
                    parsed.searchParams.set(paramKey, '[REDACTED]');
                }
            }
            return parsed.toString();
        } catch {
            return url; // Fallback to original on parse errors
        }
    }
}

/**
 * Global instance for Activepieces context execution.
 * Throws an error if accessed before being fully initialized by the host platform to prevent null panics.
 */
let _httpClientInstance: HostHttpClient | null = null;

export function initializeHttpClient(
    tokenManager: TokenManagerService,
    db: DrizzleDb,
    redis: Redis
) {
    _httpClientInstance ??= new HostHttpClient(tokenManager, db, redis);
}

export const httpClient = new Proxy({} as HostHttpClient, {
    get: (_target, prop) => {
        if (!_httpClientInstance) {
            throw new InternalServerErrorException('HostHttpClient accessed before platform initialization');
        }
        const value = (_httpClientInstance as any)[prop];
        // Bind methods to the instance to ensure `this` works inside sendRequest
        if (typeof value === 'function') {
            return value.bind(_httpClientInstance);
        }
        return value;
    }
});
